<?xml version="1.0"?>
<package format="3">
  <name>sonopet</name>
  <version>0.1.0</version>
  <description>Sonopet DAQ and footpedal control for cutting-interval artifacts.</description>
  <maintainer email="victor@example.com">Victor Xia</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python3-serial</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
