cameras:
  in_hand:
    serial: "323622273258"
    namespace: RealSense_D405
    camera_name: in_hand
    parent_frame: fr3_link8
    color_optical_frame: in_hand_color_optical_frame
    depth_optical_frame: in_hand_depth_optical_frame
    translation_xyz: [0.007746960142, -0.135801184373, 0.014861]
    quaternion_xyzw: [-0.011749712059, -0.119807893418, 0.992711849055, 0.006596208292]
    planning_source: true
  fixed:
    serial: "427622272709"
    namespace: RealSense_D405
    camera_name: fixed
    parent_frame: fr3_link0
    color_optical_frame: fixed_color_optical_frame
    depth_optical_frame: fixed_depth_optical_frame
    translation_xyz: [0.448819, 0.28769, 0.303049]
    quaternion_xyzw: [-0.36791, 0.848564, -0.377844, -0.0426032]
    planning_source: false

realsense:
  rgb_camera_profile: 848x480x30
  depth_module_profile: 848x480x30
  fps: 30.0

pointcloud_snapshots:
  timeout_sec: 5.0
