raster:
  target_frame: fr3_link0
  planning_cloud_topic: /sonopet/captured_planning_cloud
  planning_cloud_display_topic: /sonopet/planning_cloud
  clicked_point_topic: /clicked_point
  square_side_m: 0.02
  line_spacing_m: 0.002
  downsample_rate: 6
  pattern: unidirectional_retract
